SnippetsHub/SnippetsHub/Controllers/AdvertisingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SnippetsHub.Models;
using System.Data;

namespace SnippetsHub.Controllers
{
    public class AdvertisingController : Controller
    {
        
        static DataSet ds;
        static DataTable dt;

        // GET: Advertising
        public ActionResult Index()
        {
            if (System.IO.File.Exists(Server.MapPath(@"~/advertising.xml")))
            {

                ds = new DataSet();
                ds.ReadXml(Server.MapPath(@"~/advertising.xml"));
                dt = ds.Tables[0];

            }
            else
            {
                ds = new DataSet("AdvertisingPitches");
                dt = new DataTable("AvertisingPitch");
                dt.Columns.Add("CompanyName");
                dt.Columns.Add("CompanyContactPerson");
                dt.Columns.Add("ContactPersonEmail");
                dt.Columns.Add("AdvertisingIdea");
                ds.Tables.Add(dt);

            }

            return View();
        }

        [HttpPost]
        public ActionResult Advertising(AdvertisingModel advertising)
        {

            if (ModelState.IsValid)
            {
                DataRow row = dt.NewRow();
                row["CompanyName"] = advertising.CompanyName;
                row["CompanyContactPerson"] = advertising.CompanyContactPerson;
                row["ContactPersonEmail"] = advertising.ContactPersonEmail;
                row["AdvertisingIdea"] = advertising.AdvertisingIdea;
                dt.Rows.Add(row);

                ds.WriteXml(Server.MapPath(@"~/advertising.xml"));

                ViewData["message"] = "Thanks for your advertising Pitch. We will review it and contact you shortly";
                return View("ThankYou");
            }
            else return View("Index", advertising);
        }

       
    }
}

SnippetsHub/SnippetsHub/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;



namespace SnippetsHub.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AboutUs()
        {
            return View();
        }

        public ActionResult SiteMap()
        {
            return View();
        }

        public ActionResult FrequentlyAskedQuestions()
        {
            return View();
        }




    }
}

SnippetsHub/SnippetsHub/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SnippetsHub.Models;

namespace SnippetsHub.Controllers
{
    public class MemberController : Controller
    {
        
        DAO dao = new DAO();
        
        // GET: Member
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult RegistrationPage()
        {
            return View();
        }
       
        public ActionResult Snippet()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        public ActionResult CreateGroup()
        {
            return View();
        }

        public ActionResult Group()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(Member member)
        {
            int count;
            if (ModelState.IsValid)
            {
                count = dao.Insert(member);
                if (count > 0)
                {
                    ViewData["message"] = "Registered Successfully";
                }
                else ViewData["message"] = "Error: " + dao.message;
                return View("Message");
            }

            else return View("RegistrationPage", member);
        }
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginModel login)
        {
            Member member = new Member();
            if (ModelState.IsValid)
            {
                member.Email = login.Email;
                member.Password = login.Password;
                member.FirstName = dao.CheckLogin(member);

                Session.Add("memberName", member.FirstName);
                Session.Add("memberEmail", member.Email);

                if (Session["memberName"] == null)
                {
                    ViewData["message"] = "Error: " + dao.message;
                    return View("Message");
                }

                return View("Snippet");
             
            }
            else return View("Login");      
        }

        public ActionResult LogOff()
        {

            Session.Clear();
            return View("Login");
        }

  
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult CreateSnippet(Snippet snippet)
        {
            int count;
            snippet.Email = Session["memberEmail"].ToString();
            //attempts to show snippets in the correct format 
            // Overwrite the newline characters with html equivalents, to preserve the snippet format
            //snippet.Content = snippet.Content.Replace("\r\n", "<br />");
            if (ModelState.IsValid)
            {               
                count = dao.InsertSnippet(snippet);
                if (count > 0)
                {
                    ViewData["message"] = "Snippet created successfully";
                }
                else ViewData["message"] = "Error: " + dao.message;
                return View();
            }

            return View("Index", snippet);
        }

        public ActionResult ShowSnippets()
        {           
            List<Snippet> list = dao.ShowAllSnippets(Session["memberEmail"].ToString());
            return View(list);
        }

        [HttpPost]
        public ActionResult NewGroup(Group group)
        {
                int count;
            if (ModelState.IsValid)
            {
                count = dao.InsertGroup(group);
                if (count > 0)
                {
                    ViewData["message"] = "Group created successfully";
                }
                else ViewData["message"] = "Error: " + dao.message;
                return View("Snippet");
            }

            else return View("Index", group);
        }

        public ActionResult MyGroups()
        {
            // just display view
            string email = Session["memberEmail"].ToString();
            List<Group> myGroups = dao.ShowMemberGroups(email);
            return View(myGroups);
        }

        [HttpPost]
        public ActionResult MyGroups(string groupName)
        {
            string email = Session["memberEmail"].ToString();
            if (groupName != null)
            {
                List<Group> grouplist = dao.FindGroups(groupName); 
                if(grouplist.Count > 0)
                {
                    dao.InsertintoGroupMembers(grouplist[0], email);
                }          
            }
            List<Group> myGroups = dao.ShowMemberGroups(email);
            return View(myGroups);
           
        }

        [HttpPost]
        public ActionResult GetGroupPage(string groupName)
        {
            Snippet snippet = new Snippet();
            snippet.GroupName = groupName;
            return View("GroupPage", snippet);
           
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult GroupPage(Snippet snippet)
        {
            snippet.Email = Session["memberEmail"].ToString();
            dao.InsertSnippet(snippet);
            return View("SnippetAddedSuccessfully");     
        }

        [HttpPost]
        public ActionResult ShowGroupSnippets(string groupName)
        {
            List<Snippet> list = dao.ShowGroupSnippets(groupName);
            return View(list);
        }


    }
}

SnippetsHub/SnippetsHub/Views/Home/AboutUs.cshtml
@{
    ViewBag.Title = "AboutUs";
}  
          
    <div class="text-center">    
            <h3> Our Story</h3>
            <p> Snippets Hub was founded by Ruth Kerr, Sarah Morley and Criag O'Sullivan in August 2016.</p>
            <p> Origianlly set up as a college project it has gone from strength to strength ever since and is now one of the most used code sharing applications.</p>
            <p> Snippets Hub is currently being used by over 200,000 people all over the world.</p>  
        <p> Hello Sarah</p>
        </div>
     <p class="text-center"><img id="award" img src="~/Images/award.jpeg" /></p>

SnippetsHub/SnippetsHub/Views/Home/FrequentlyAskedQuestions.cshtml
@{
    ViewBag.Title = "FrequentlyAskedQuestions";
}


<div class="text-center">
    <h2>FrequentlyAskedQuestions</h2>

    <ul style="list-style-type:none;" id="questions">
        <li>1. Is Snippet Hub free&#63;</li>
        <p>You can register to use Snippet Hub for free. You will be able to create snippets, and view and use other snippets for free.</p>
        <li>2. Are profiles public or private&#63;</li>
        <p>You can choose who can view your snippets by making your profile public or private.</p>
        <li>3. Can I join several groups&#63;</li>
        <p>Yes you can join as many groups as you like. </p>
    </ul>
</div>

SnippetsHub/SnippetsHub/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}   


<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <h3>Welcome</h3>
            <img src="~/Images/home1.png" width="250"/>
            <p> Welcome to Snippet Hub, a completely free code sharing application built by coders for coders. Sign up today to save all your imporatnt code snipepts in one free place.</p>
        </div>
        <div class="col-sm-4">
            <h3>Groups</h3>
            <img src="~/Images/home2.png" width="250"/>
            <p>Snippet Hub allows you to create groups among fellow developers where members can share code snippets. Members can join as many groups as they wish. 
             </p>
        </div>
        <div class="col-sm-4">
            <h3>Personal</h3>
            <img src="~/Images/home3.jpg" width="250" />

            <p> This is a new paragraph </p>

        </div>
    </div>
</div>

SnippetsHub/SnippetsHub/Views/Home/SiteMap.cshtml
@{
    ViewBag.Title = "SiteMap";
}

<h2>SiteMap</h2>

<ul>
    <li> @Html.ActionLink("Home", "Index", "Home") </li> 
    <li> @Html.ActionLink("About Us", "AboutUs", "Home")</li> 
    <li> @Html.ActionLink("FAQ", "FrequentlyAskedQuestions", "Home")</li>
    <li> @Html.ActionLink("Interested in Advertising?", "Index", "Advertising")</li>
    <li> @Html.ActionLink("Register", "RegistrationPage", "Member")</li>
    <li> @Html.ActionLink("Login", "Login", "Member")</li>
    <li> @Html.ActionLink("MyProfile", "Snippet", "Member")</li>
</ul>